version: '3.8'
services:
  kanban-task-manager:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
      - "8080:8080"
    env_file:
      - .env-springboot
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver

  mysqlserver:
    image: mysql:8.0
    ports:
      - "3307:3306"
    env_file:
      - .env-mysql
    volumes:
      - ./kanban-task-manager-DB:/docker-entrypoint-initdb.d